name: CI/CD Pipeline (Test + Deploy)

on:
  push:
    branches: ["main"]  # Full CI/CD on main branch
  pull_request:         # Only run tests on PRs
  workflow_dispatch:    # Allow manual triggers

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # --- CI: BUILD & TEST (Runs on every push/PR) ---
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js (adjust for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Install dependencies & run tests
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test  # Fails pipeline if tests fail

  # --- CD: DEPLOY (Only runs on main branch if tests pass) ---
  deploy:
    name: Deploy to GitHub Pages
    needs: test  # Waits for test job to succeed
    if: github.ref == 'refs/heads/main'  # Extra safety
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
